import './globals.css'
import { Inter } from 'next/font/google'
import { ReactNode } from "react"
import type { AppProps } from "next/app"
// import {MDXProvider} from "@mdx-js/react"

function H1(props: {children: ReactNode}){
    return <h1 className="text-3xl font-bold">{props.children}</h1>
}

function P(props: {children?: ReactNode}) {
    return <p className="p-3">{props.children}</p>
  }

const components = {
  h1: H1,
  p: P,
}

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
        <body className={inter.className}>
          <h1 className="text-3xl">Reactの資料だゾ</h1>
          {children}
        </body>
    </html>
  )
}
